modLoader="javafml"
loaderVersion="[36.2,)"
license="GNU GPLv3"

[[mods]]
modId="ahutils"
version="${ahutils_version}"
updateJSONURL="https://hi.auioc.org/ahutils-mod/update/1.16.5.json"
displayName="AHUtils"
credits="AUIOC"
authors="WakelssSloth56"
description='''
${ahutils_description}
'''

[[dependencies.ahutils]]
    modId="forge"
    mandatory=true
    versionRange="[36.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ahutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
