modLoader="javafml"
loaderVersion="[36.2,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/WakelessSloth56/ahutils-mod/issues"

[[mods]]
modId="ahutils"
version="${ahutils_version}"
updateJSONURL="https://hi.auioc.org/ahutils-mod/update/1.16.5.json"
displayName="AHUtils"
displayURL="https://github.com/WakelessSloth56/ahutils-mod"
credits="AUIOC"
authors="WakelssSloth56"
description='''
Minecraft utilities, also a library for AH's mods.
${ahutils_full_version}
'''

[[dependencies.ahutils]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ahutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
